import { MapPinned, ArrowUpRight, Navigation, Droplets, Building2, ArrowRight, ShieldCheck } from 'lucide-react'

export default function LandingPage({ navigate, signedIn, municipal }) {
  return <div className="portal landing-page">
    <header className="portal-header"><a className="portal-brand" href="#/"><MapPinned size={27} /><strong>JalMarg</strong></a><nav aria-label="Website navigation"><a href="#how-it-works">How it works</a><button onClick={() => navigate(municipal ? 'municipal' : 'access')}>Municipal access<ArrowUpRight size={16} /></button><button className="portal-login" onClick={() => navigate(signedIn ? 'account' : 'signin')}>{signedIn ? 'My account' : 'Sign in'}</button></nav></header>
    <main><section className="landing-hero"><div className="hero-copy"><span className="landing-eyebrow">A clearer way through the monsoon</span><h1>Know the road.<br />Help clear the way.</h1><p>Waterlogging reports that guide your journey and help municipal teams act.</p><div className="landing-actions"><md-filled-button onClick={() => navigate('map')}>Explore the map<Navigation size={18} slot="icon" /></md-filled-button><button className="landing-text-link" onClick={() => navigate(signedIn ? 'account' : 'signup')}>{signedIn ? 'Track my reports' : 'Create citizen account'}<ArrowRight size={18} /></button></div></div><figure className="landing-preview"><img src="/journey-preview.jpg" alt="JalMarg map showing named journey endpoints and waterlogging-aware directions" fetchPriority="high" /><figcaption>A look inside JalMarg. Observations and journey times vary.</figcaption></figure></section>
      <section id="how-it-works" className="landing-process"><div><h2>One report.<br />A connected response.</h2><p>From a road observation to a visible work update, everyone has a part to play.</p></div><ol><li><Droplets size={23} /><div><h3>See it. Report it.</h3><p>Share a location, what you observed and an optional recent photo.</p></div></li><li><Navigation size={23} /><div><h3>Choose your next turn.</h3><p>Compare routes against recent reports and your selected vehicle.</p></div></li><li><Building2 size={23} /><div><h3>Follow the response.</h3><p>Verified municipal teams review, assign and update work. You can follow your report.</p></div></li></ol></section>
      <section className="landing-municipal"><ShieldCheck size={34} /><div><h2>A workspace for the people clearing our roads.</h2><p>Review local reports, coordinate assignments and document completed work with evidence.</p></div><button className="secondary-button" onClick={() => navigate(municipal ? 'municipal' : 'access')}>{municipal ? 'Open workspace' : 'Request municipal access'}<ArrowRight size={18} /></button></section>
      <aside className="landing-note">Community observations are approximate and may be incomplete. Route guidance does not establish that a flooded road is safe to cross.</aside>
    </main><footer className="portal-footer"><span>JalMarg · Built for the monsoon</span><a href="#/map">Open map<ArrowUpRight size={15} /></a></footer>
  </div>
}
